# **Notebook 10 – Combining Datasets**

## **1. concat()**



**Understand the Concept**

* concat() is used to combine two or more DataFrames.
* It can combine DataFrames vertically (rows) or horizontally (columns).
* By default, it combines DataFrames row-wise.

**Demonstrate the Concept**

**Example:**

* One dataset contains existing customers.
* Another dataset contains new customers.
* concat() combines both datasets into one DataFrame.


**AI/ML Usage:**

* `concat()` is used to combine datasets from multiple sources before data preprocessing and model training.

In [1]:
# Libraries: 
import pandas as pd

In [2]:
# Load Dataset: 
customers = pd.read_csv("customers_dataset.csv")
customers.head(3)

  Customer_ID first_name last_name        City                       mail
0    CUST0001      Arjun     Kumar   Hyderabad   arjun.kumar1@example.com
1    CUST0002     Vikram     Patel  Coimbatore  vikram.patel2@example.com
2    CUST0003      Arjun     Brown   Bengaluru   arjun.brown3@example.com

In [4]:
# Implement the Concept:
# New customers data 
new_customers = pd.DataFrame({"Customer_ID" : ["CUST0501", "CUST0502"],
                              "first_name": ["Arun", "Kiran"],
                              "last_name": ["Kumar", "Das"],
                              "City": ["Chennai", "Pune"],
                              "mail": ["arun.kumar501@example.com", "kiran.das502@example.com"]})
new_customers

  Customer_ID first_name last_name     City                       mail
0    CUST0501       Arun     Kumar  Chennai  arun.kumar501@example.com
1    CUST0502      Kiran       Das     Pune   kiran.das502@example.com

In [7]:
# Combine both DataFrames
combined_customers = pd.concat([customers,new_customers], ignore_index = True)
combined_customers.tail()

    Customer_ID first_name last_name       City                          mail
497    CUST0498      Rahul     Reddy    Madurai    rahul.reddy498@example.com
498    CUST0499      Rohan   Johnson  Hyderabad  rohan.johnson499@example.com
499    CUST0500      Priya      Iyer  Bengaluru     priya.iyer500@example.com
500    CUST0501       Arun     Kumar    Chennai     arun.kumar501@example.com
501    CUST0502      Kiran       Das       Pune      kiran.das502@example.com

**Interpretation**

* concat() combines the existing customer data with the new customer records.
* The new rows are added below the existing 500 rows.
* The final DataFrame contains 502 rows.
* ignore_index=True creates a new continuous index.

## **2. merge()**



**Understand the Concept**

* merge() is used to combine two DataFrames based on a common column or key.
* It works similarly to SQL joins.
* Common merge types:
    * inner join - Returns only matching records from both DataFrames.
    * left join - Returns all records from the left dataset and matching records from the right.
    * right join - Returns all records from the right dataset and matching records from the left.
    * outer join - Returns all records from both dataset, including non-matching records.

**Demonstrate the Concept**

**Example:**

* One dataset contains customer information.
* Another dataset contains order information.
* Both datasets contain Customer_ID.
* merge() combines the matching records using Customer_ID.

**Real-Life Example:**

* A company stores customer details and order details in separate datasets.
* merge() can combine both datasets for customer order analysis.

**AI/ML Usage:**

* merge() is used to combine features from different datasets before data preprocessing and model training.

In [9]:
# orders data
orders = pd.DataFrame({"Order_ID": ["ORD001", "ORD002", "ORD003", "ORD004", "ORD005"],
                       "Customer_ID": ["CUST0001", "CUST0002", "CUST0003", "CUST0004", "CUST0005"],
                       "Product": ["Laptop", "Mobile", "Headphones", "Keyboard", "Mouse"],
                       "Order_Value": [65000, 30000, 2500, 3500, 1200]})
orders

  Order_ID Customer_ID     Product  Order_Value
0   ORD001    CUST0001      Laptop        65000
1   ORD002    CUST0002      Mobile        30000
2   ORD003    CUST0003  Headphones         2500
3   ORD004    CUST0004    Keyboard         3500
4   ORD005    CUST0005       Mouse         1200

In [11]:
# Implement the Concept:
# Merge - customers & orders dataset 
customer_orders = pd.merge(customers, orders, on="Customer_ID", how="inner")
customer_orders

,Customer_ID,first_name,last_name,City,mail,Order_ID,Product,Order_Value
0,CUST0001,Arjun,Kumar,Hyderabad,arjun.kumar1@example.com,ORD001,Laptop,65000
1,CUST0002,Vikram,Patel,Coimbatore,vikram.patel2@example.com,ORD002,Mobile,30000
2,CUST0003,Arjun,Brown,Bengaluru,arjun.brown3@example.com,ORD003,Headphones,2500
3,CUST0004,Sarah,Gupta,Chennai,sarah.gupta4@example.com,ORD004,Keyboard,3500
4,CUST0005,Aarav,Sharma,Madurai,aarav.sharma5@example.com,ORD005,Mouse,1200

**Interpretation**

* merge() combines the customers and orders dataset.
* Customer_ID is used as the common column.
* Only records with matching Customer_ID values are included because how="inner" is used.
* The result contains customer details along with their order information.

## **3. join()**



**Understand the Concept**

* join() is used to combine two dataset based on their index by default.
* It can also combine dataset using a common column.

**Demonstrate the Concept**

**Real-Life Example:**

* A company stores customer details and membership details separately.
* join() can combine both datasets into a single DataFrame.

**AI/ML Usage:**

* join() can be used to combine related features from multiple datasets before data preprocessing and model training.

In [12]:
# membership ddta
membership = pd.DataFrame({"Customer_ID" :["CUST0001","CUST0002","CUST0003","CUST0004","CUST0005"],
                           "Membership": ["Gold", "Silver", "Gold", "Platinum", "Silver"]})
membership

  Customer_ID Membership
0    CUST0001       Gold
1    CUST0002     Silver
2    CUST0003       Gold
3    CUST0004   Platinum
4    CUST0005     Silver

In [21]:
# Implement the Concept:
# join() - join customers & membership using common col 
customer_membership = customers.join(membership.set_index("Customer_ID"), on = "Customer_ID")
customer_membership[2:8]

,Customer_ID,first_name,last_name,City,mail,Membership
2,CUST0003,Arjun,Brown,Bengaluru,arjun.brown3@example.com,Gold
3,CUST0004,Sarah,Gupta,Chennai,sarah.gupta4@example.com,Platinum
4,CUST0005,Aarav,Sharma,Madurai,aarav.sharma5@example.com,Silver
5,CUST0006,Vikram,Nair,Chennai,vikram.nair6@example.com,NaN
6,CUST0007,Michael,Patel,Delhi,michael.patel7@example.com,NaN
7,CUST0008,Vikram,Das,Hyderabad,vikram.das8@example.com,NaN

**Interpretation**

* join() combines the customers and membership data using Customer_ID.
* Customer_ID acts as the common column between both data.
* The Membership information is added to the matching customer records.
* Customers without matching membership information will contain missing values.

## **4. append()**



**Understand the Concept**

* append() was used to add rows from one DataFrame to another.
* data_1.append(data_2) is deprecated and removed in newer Pandas versions.
* The recommended alternative is pd.concat([d1,d2]).

**Demonstrate the Concept**

**Real-Life Example:**

* A company receives new customer records and needs to add them to the existing customer dataset.
* pd.concat() combines the existing and new records.

**AI/ML Usage:**

* pd.concat() is used to combine new data with existing datasets during data collection and preprocessing.

In [24]:
# new customers data 
new_customers # already define

  Customer_ID first_name last_name     City                       mail
0    CUST0501       Arun     Kumar  Chennai  arun.kumar501@example.com
1    CUST0502      Kiran       Das     Pune   kiran.das502@example.com

In [25]:
# Implement the Concept: 
# concat() - customers & new_customers
updated_customers = pd.concat([customers, new_customers],ignore_index=True)
print(updated_customers.tail())

    Customer_ID first_name last_name       City                          mail
497    CUST0498      Rahul     Reddy    Madurai    rahul.reddy498@example.com
498    CUST0499      Rohan   Johnson  Hyderabad  rohan.johnson499@example.com
499    CUST0500      Priya      Iyer  Bengaluru     priya.iyer500@example.com
500    CUST0501       Arun     Kumar    Chennai     arun.kumar501@example.com
501    CUST0502      Kiran       Das       Pune      kiran.das502@example.com

**Interpretation**

* DataFrame.append() is deprecated and should not be used in newer Pandas versions.
* pd.concat() is the recommended alternative for adding rows from one dataset to another.

## **5. combine_first()**



**Understand the Concept**

* combine_first() is used to combine two DataFrames and fills missing values in one DataFrame using values from another DataFrame.
* Existing non-missing values in the first DataFrame are kept unchanged.

**Demonstrate the Concept**

**Example:**

* One customer dataset contains missing City and mail values.
* Another dataset contains the missing information.
* combine_first() fills the missing values using the second DataFrame.

**Real-Life Example:**

* A company has incomplete customer records in one dataset and updated information in another dataset.
* combine_first() can fill the missing details from the updated dataset.

**AI/ML Usage:**

* combine_first() can be used to fill missing values by combining information from multiple datasets during data preprocessing.

In [43]:
# Implement the Concept: 
# customer data with missing values
customers_1 = pd.DataFrame({"Customer_ID": ["CUST0001", "CUST0002", "CUST0003","CUST0004"],
                            "City": ["Chennai", None, "Mumbai","Coimbatore"],
                            "mail": ["arjun@example.com", None, "rahul@example.com",None]})
customers_1

  Customer_ID        City               mail
0    CUST0001     Chennai  arjun@example.com
1    CUST0002        None               None
2    CUST0003      Mumbai  rahul@example.com
3    CUST0004  Coimbatore               None

In [44]:
# customer data with non-missing values
customers_2 = pd.DataFrame({"Customer_ID": ["CUST0001", "CUST0002", "CUST0003","CUST0005"],
                            "City": ["Chennai", "Bengaluru", "Mumbai","Dehli"],
                            "mail": ["arjun@example.com","vikram@example.com","rahul@example.com","navin@emanple.com"]})
customers_2

  Customer_ID       City                mail
0    CUST0001    Chennai   arjun@example.com
1    CUST0002  Bengaluru  vikram@example.com
2    CUST0003     Mumbai   rahul@example.com
3    CUST0005      Dehli   navin@emanple.com

In [45]:
# index - both data customer_id is a index 
customers_1 = customers_1.set_index("Customer_ID")
customers_2 = customers_2.set_index("Customer_ID")

In [46]:
# combine_first - fill missing values using 2nd data
combined_customers = customers_1.combine_first(customers_2)
print(combined_customers)

                   City                mail
Customer_ID
CUST0001        Chennai   arjun@example.com
CUST0002      Bengaluru  vikram@example.com
CUST0003         Mumbai   rahul@example.com
CUST0004     Coimbatore                 NaN
CUST0005          Dehli   navin@emanple.com

**Interpretation**

* combine_first() keeps the existing values from customers_1.
* Missing values in customers_1 are filled using matching values from customers_2.
* For CUST0002, the missing City and mail values are filled from customers_2.
* CUST0004 exists only in customers_1, so its missing mail value remains NaN.
* CUST0005 exists only in customers_2, so it is added to the combined DataFrame.

## **Best Practices**

* Use concat() to combine DataFrames row-wise or column-wise.
* Use merge() when DataFrames have a common column or key.
* Use join() when combining DataFrames based on an index or common column.
* Use pd.concat() instead of the deprecated append() method.
* Use combine_first() to fill missing values from another DataFrame.
* Check the result after combining datasets to identify missing or duplicate records.

## **Common Mistakes**

* Using the wrong common column while merging DataFrames.
* Forgetting to check for duplicate keys before merge().
* Confusing concat() with merge().
* Using append() in newer Pandas versions.
* Not checking missing values after combining datasets.
* Using the wrong join type.

## **Advantages**

* Combines information from multiple datasets.
* Helps create complete datasets for analysis.
* Supports different types of joins and combinations.
* Useful for data integration and preprocessing.
* Helps prepare data from multiple sources for AI/ML.

## **Limitations**

* Incorrect keys can produce incorrect results.
* Duplicate keys can create unexpected repeated rows.
* Large merge operations can require more memory.
* Missing values may appear when records do not match.


## **Interview Questions with Answers**

**1. What is concat() in Pandas?**

* concat() is used to combine two or more DataFrames along rows or columns.

**2. What is the difference between concat() and merge()?**

* concat() combines DataFrames based on an axis, while merge() combines DataFrames using a common column or key.

**3. What are the common types of merge?**

* inner join returns matching records from both DataFrames.
* left join returns all records from the left DataFrame and matching records from the right.
* right join returns all records from the right DataFrame and matching records from the left.
* outer join returns all records from both DataFrames.

**4. What is join() used for?**

* join() is used to combine DataFrames based on their index by default or using a specified common column.

**5. Why should append() not be used in newer Pandas versions?**

* DataFrame.append() is deprecated and removed in newer Pandas versions. pd.concat() is the recommended alternative.

**6. What does combine_first() do?**

* combine_first() fills missing values in one DataFrame using corresponding values from another DataFrame.

**7. What happens when merge() finds no matching values?**

* The result depends on the join type. Inner join removes non-matching records, while left, right, and outer joins can include them with missing values.

## **Self Reflection**

* I learned how to combine DataFrames using concat().
* I practiced combining datasets using merge() and different join types.
* I learned how join() works with indexes and common columns.
* I understood why append() is deprecated and how pd.concat() can be used instead.
* I practiced filling missing values using combine_first().
* I understood how combining datasets is useful for data analysis and AI/ML.